version: '3.8'

services:
  frontend:
    container_name: mern-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs/
      - ./public:/app/public/
    env_file:
      - .env